## This file contains two functions, makeCacheMatrix and cacheSolve.


## makeCacheMatrix generates a list of functions for accessing a matrix
# and its inverse.

makeCacheMatrix <- function(x = matrix()) {
  inv <- NULL
  set <- function(y){
    x <<- y
    inv <<- NULL
  }
  
  get <- function() x
  setInv <- function(invMat) inv <<- invMat
  getInv <- function() inv
  
  #This is the final computed value, and thus the return value for the function
  list(set = set, get = get, setInv = setInv, getInv = getInv)
}


## cacheSolve takes a list of functions generated by makeCacheMatrix
# to compute the inverse of a matrix if it hasn't already been computed, 
#and to access the inverse, otherwise.

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
  inv <- x$getInv()
  
  
  if(!is.null(inv)) {
    message("getting cached data")
    return(inv)
  }
  
  # If the inverse has already been computed, the return function in the
  #previous means the following matrix computation won't be completed.
  mat <- x$get()
  inv <- solve(mat)
  x$setInv(inv)
  inv
}
